### ISSUE TITLE
No response types

### ISSUE THREAD

**Issue by sarimabbas** [microlinkhq/mql#131]
Hello! Thanks for your work on this library. On the current version `0.10.34`, there do not seem to be any response types. Do you have any suggestions for how to type the response in typescript? thanks so much!

Code sample:

```
   const { status, data } = await mql("https://google.com", {
      meta: true,
    });
```

`status` and `data` give errors like: `Property data does not exist on type {}.`

**Comment by Kikobeats** [comment]
@sarimabbas Thanks for reporting; I published a new version that adds the missing types.

Can you confirm `@microlink/mql@0.10.35` works fine at your end? 🙂

**Comment by sarimabbas** [comment]
Sorry for the delay! I can confirm the new version works fine on my end. thanks so much!
