### ISSUE TITLE
TypeScript declaration file

### ISSUE THREAD

**Issue by lachenmayer** [microlinkhq/mql#25]
Hey there, as I've mentioned to you in support, we're using TypeScript & currently it's not possible to import this module in strict mode, as there are no type definitions.

It would be ideal if the library could expose a `index.d.ts` file so that TypeScript users can use this. As a bonus, this would allow users of VS Code to get autocomplete suggestions even if they're using JavaScript.

I've written the following declaration file for our project, which could be a good starting point for an `index.d.ts` file:

```typescript
/// <reference types="node" />

declare module '@microlink/mql' {
  export type WaitUntilEvent =
    | 'load'
    | 'domcontentloaded'
    | 'networkidle0'
    | 'networkidle2'

  export type ScreenshotOptions = Partial<{
    background: string
    browser: 'light' | 'dark'
    click: string | string[]
    deviceScaleFactor: number
    disableAnimations: boolean
    emulation: string
    fullPage: boolean
    hasTouch: boolean
    height: number
    hide: string | string[]
    isLandscape: boolean
    isMobile: boolean
    scrollTo: string
    type: 'jpeg' | 'png'
    waitFor: number | string
    waitUntil: WaitUntilEvent | WaitUntilEvent[]
    width: number
  }>

  export type MqlQueryResponseType =
    | 'author'
    | 'date'
    | 'description'
    | 'image'
    | 'title'
    | 'url'
    | 'lang'
    | 'publisher'

  export type MqlQueryOptions = Partial<{
    attr: string | string[]
    selector: string | string[]
    selectorAll: string | string[]
    type: MqlQueryResponseType
  }>

  export interface MqlQuery {
    [field: string]: MqlQueryOptions
  }

  export type MicrolinkApiOptions = Partial<{
    audio: boolean
    data: MqlQuery
    embed: string
    filter: string
    force: boolean
    headers: object
    meta: boolean
    palette: boolean
    prerender: boolean | 'auto'
    proxy: string
    screenshot: boolean | ScreenshotOptions
    ttl: string | number
    url: string
    video: boolean
  }>

  export type MqlOptions = Partial<{
    apiKey: string
    retry: number
    cache: Map<string, any>
    timeout: number
  }>

  export interface ImageInfo {
    width: number
    height: number
    type: string
    size: number
    size_pretty: string
  }

  export interface PlayableMediaInfo extends ImageInfo {
    duration: number
    duration_pretty: string
  }

  export type MqlResponseData = Partial<{
    author: string
    date: string
    description: string
    video: string
    lang: string
    publisher: string
    title: string
    url: string
    image: ImageInfo
    logo: ImageInfo
    video: PlayableMediaInfo
    audio: PlayableMediaInfo
  }>

  export type MqlStatus = 'success' | 'fail'

  export interface MqlResponse {
    status: MqlStatus
    data: MqlResponseData
    response: Response
  }

  declare function mql(url: string, opts?: MqlOptions & MicrolinkApiOptions): Promise<MqlResponse>

  declare namespace mql {
    export class MicrolinkError extends Error {}
  }

  export = mql
}
```

I've written this based on the documentation on the Microlink website. There were a couple of cases where the documentation was incorrect (eg. the `cache` option), so I've used a best guess based on the examples provided on the website.

I haven't massively tested this beyond our pretty simple use case, but as far as I know this is working for us.

There are a bunch of APIs that I didn't expose in here (`getApiUrl`, `fetchFromApi`, etc.), as I don't see us using these at the moment. A "official" `index.d.ts` file should of course include these.

Thanks a lot for this service, it's super helpful!

**Comment by goleary** [comment]
Seconded, it would be AWESOME if this could be added to the library.

Thanks for posting this @lachenmayer I'll start with what you've got and report back if I find that any modifications are needed.

**Comment by Kikobeats** [comment]
Any PR about types is very welcome 🙂

**Comment by goleary** [comment]
cool, will report back once I've had some time to play with it.

**Comment by Kikobeats** [comment]
I close this because I'm not an active TypeScript user. A PR for this is still very welcome!
