### ISSUE TITLE
Incorrect use of `module` field in `package.json`

### ISSUE THREAD

**Issue by charsleysa** [microlinkhq/mql#50]
Currently the `module` field in `package.json` is pointing to the browser only implementation of this library meaning modern bundling tools that bundle for Node.js are importing the wrong code.

Also the `module` field should be used only for ESModule compliant code, which looking at the source code this is not the case.

My recommendation would be to just remove `module` field from `package.json`.

**Comment by Kikobeats** [comment]
Thanks, shipped at `@microlink/mql@0.6.5` 🙂
