### ISSUE TITLE
Better types

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/mql#79]
There are some TODO's to improve types detection based on the context environment

- https://github.com/microlinkhq/mql/blob/master/index.d.ts#L144
- https://github.com/microlinkhq/mql/blob/master/index.d.ts#L156

**Comment by goleary** [comment]
additionally, the function prop is missing from the `opts` type.

**Comment by goleary** [comment]
The types that were added actually broke our environment due to how we use mql (which was typeless before)

![image](https://user-images.githubusercontent.com/16123225/142964309-2fd1b712-465a-4e04-b704-98a38ba7aace.png)

**Comment by goleary** [comment]
The media return types are also incorrect

![image](https://user-images.githubusercontent.com/16123225/142964440-5c54d4e5-1488-4ea0-96cd-a066a0991f2f.png)

Just realized that I have types I've been using internally that probably should've been contributed back to this project

https://gist.github.com/goleary/d2a99c345695db21d9f1f27524f47c40

**Comment by goleary** [comment]
went ahead and created #81 by combining what's here with the types I've been maintaining on my end.
